version: '3.9'

services:
  db:
    image: postgres:16
    container_name: meu-caramelo-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meu_caramelo_production
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    container_name: meu-caramelo-app
    command: bash -c "bundle exec rails db:prepare && bundle exec rails s -b 0.0.0.0 -p 8080"
    volumes:
      - .:/rails
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      POSTGRES_PASSWORD: postgres
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}

volumes:
  postgres-data:
