app = "meu-caramelo-v2"
primary_region = "gru"

[build]
  # Exemplo de comandos de build para Rails
  [build.args]
    BUNDLER_VERSION = "2.4.19"
    NODE_VERSION = "18.18.0"
    RUBY_VERSION = "3.2.2"

[env]
  PORT = "8080"
  RACK_ENV = "production"
  RAILS_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
