app = "meu-caramelo-v2"
primary_region = "gru"

[build]
  [build.args]
    BUNDLER_VERSION = "2.4.19"
    NODE_VERSION = "18.18.0"
    RUBY_VERSION = "3.1.4"

[env]
  PORT = "8080"
  RAILS_ENV = "production"
  WEB_CONCURRENCY = "1"
  RAILS_MAX_THREADS = "2"
  RAILS_MIN_THREADS = "2"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/health"
    protocol = "http"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[deploy]
  # release_command = "rails db:prepare"
